# -*- coding: utf-8 -*-
"""Decisiontree.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ck1iTb-ncmgyUkacWYKqO6ptoYGG8pJJ

<a href="https://colab.research.google.com/github/Ritik-Gupta-675/ML-LAB-6TH-SEM/blob/main/Decisiontree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# all formulas
# entropy = -plogp
#information gain = E(parent) - (Weighted average)*E(child)

df = pd.read_csv("PlayTennis.csv")
print(df.head())

def entropy(col):
    n = len(col)
    unique_values , counts = np.unique(col,return_counts=True)
    probabilities = counts/n
    entropy = np.sum(probabilities*-np.log2(probabilities))

    return entropy

def information_gain(colName , df , target):
  unique_values , counts = np.unique(df[colName] , return_counts = True)
  entropy_list = []
  for attribute in unique_values:
    temp_df = df[df[colName] == attribute]
    entropy_list.append(entropy(temp_df[target]))
  parent_entropy = entropy(df[target])
  ig = parent_entropy - np.sum(np.array(entropy_list)*counts/len(df))
  return ig

def Decision_tree_root(df):
   columns = df.columns
   information_gain_data = {}
   target = "play"
   for col in columns:
      if(col != target):
        information_gain_data[col] = information_gain( col, df, target)
   best_feature = max(information_gain_data , key = information_gain_data.get)
   return best_feature , information_gain_data[best_feature]

root,ig = Decision_tree_root(df)

print(f"The best column to split is '{root}' with information gain {ig}.")