# -*- coding: utf-8 -*-
"""LinearRegressionscratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Rx1Wsm9N9ISNNaN79e_69qsi6CsEHUQv

<a href="https://colab.research.google.com/github/Ritik-Gupta-675/ML-LAB-6TH-SEM/blob/main/LinearRegressionscratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('Housing.csv')
df.head()
df = df[df['area']<8000]
df.head()

x = df['area']
y = df['price']
y.head()

plt.scatter(x,y)
plt.xlabel('area')
plt.ylabel('price')
plt.title('Housing Area vs Price')
plt.show()

x = x.to_numpy()
y = y.to_numpy()

x_mean = x.mean()
y_mean = y.mean()
print(x_mean)
print(y_mean)

m = ((x-x_mean)*(y-y_mean)).sum()/((x-x_mean)**2).sum()

b = y_mean - m*x_mean
print(m)
print(b)

y_pred = m*x + b

plt.scatter(x,y)
plt.plot(x,y_pred,'r-')
plt.xlabel('area')
plt.ylabel('price')
plt.title('Housing Area vs Price')
plt.show()

mse = ((y-y_pred)**2).sum()/len(y)
print(f"Mean Square Error : {mse}")

rse = 1 - ((y-y_pred)**2).sum()/((y-y_mean)**2).sum()
print(f"rse: {rse}")