# -*- coding: utf-8 -*-
"""Logicalregression1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QPr-2hN5YmK7HawcqOJB8kkP8lQ5CuUn

<a href="https://colab.research.google.com/github/Ritik-Gupta-675/ML-LAB-6TH-SEM/blob/main/Logicalregression1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_diabetes
import seaborn as sns

diabetes = load_diabetes()
X = diabetes.data
Y = diabetes.target
print(f"Diabetes data shape:{X.shape},{Y.shape}")

X = pd.DataFrame(X, columns=diabetes.feature_names)
Y = pd.DataFrame(Y, columns=["target"])

data = pd.concat([X,Y],axis=1)
sns.pairplot(data)

sns.scatterplot(x='bmi',y='target',data=data)

x=data['bmi']
y=data['target']

xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state = 1)

linearRegressor = LinearRegression()

linearRegressor.fit(xTrain.values.reshape(-1, 1), yTrain)

yPrediction = linearRegressor.predict(xTest.values.reshape(-1, 1))

plt.scatter(xTrain.values.reshape(-1, 1), yTrain.values.reshape(-1, 1), color = 'red')
plt.plot(xTrain, linearRegressor.predict(xTrain.values.reshape(-1, 1)), color = 'blue')
plt.title('BMI vs Target (Training set)')
plt.xlabel('BMI')
plt.ylabel('Target')
plt.show()

plt.scatter(xTest.values.reshape(-1, 1), yTest.values.reshape(-1, 1), color = 'red')
plt.plot(xTrain, linearRegressor.predict(xTrain.values.reshape(-1, 1)), color = 'blue')
plt.title('BMI vs Target (Testing set)')
plt.xlabel('BMI')
plt.ylabel('Target')
plt.show()

print('Coefficients: ', linearRegressor.coef_)

## % of the variance in the target variable can be explained by the BMI feature in this linear model
print('Variance score: {}'.format(linearRegressor.score(xTest.values.reshape(-1, 1), yTest)))