# -*- coding: utf-8 -*-
"""ML_LAB1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CbunoFt2ePLRIJ949A9ABlKHQwBjBNxD

<a href="https://colab.research.google.com/github/Rishi-Raj-Anand/ML_LAB/blob/main/ML_LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.datasets import load_diabetes

diabetes = load_diabetes()
X, y = diabetes.data, diabetes.target
print(f"Diabetes dataset shape: {X.shape}, {y.shape}")

X=pd.DataFrame(X,columns=diabetes.feature_names)
y=pd.DataFrame(y,columns=["target"])

data=pd.concat([X,y],axis=1)
sns.pairplot(data)

sns.scatterplot(x='bmi',y='target',data=data)

x=data['bmi']
y=data['target']

xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2, random_state = 1)

linearRegressor = LinearRegression()

linearRegressor.fit(xTrain.values.reshape(-1, 1), yTrain)

yPrediction = linearRegressor.predict(xTest.values.reshape(-1, 1))

plt.scatter(xTrain.values.reshape(-1, 1), yTrain.values.reshape(-1, 1), color = 'red')
plt.plot(xTrain, linearRegressor.predict(xTrain.values.reshape(-1, 1)), color = 'blue')
plt.title('BMI vs Target (Training set)')
plt.xlabel('BMI')
plt.ylabel('Target')
plt.show()

plt.scatter(xTest.values.reshape(-1, 1), yTest.values.reshape(-1, 1), color = 'red')
plt.plot(xTrain, linearRegressor.predict(xTrain.values.reshape(-1, 1)), color = 'blue')
plt.title('BMI vs Target (Testing set)')
plt.xlabel('BMI')
plt.ylabel('Target')
plt.show()

print('Coefficients: ', linearRegressor.coef_)

## % of the variance in the target variable can be explained by the BMI feature in this linear model
print('Variance score: {}'.format(linearRegressor.score(xTest.values.reshape(-1, 1), yTest)))